[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

description = "The lexer for the address programming language"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lexer"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
queues = "1.0.2"