[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "interpreter"
path = "src/main.rs"

[dependencies]
parser = { path = "../parser" }
common = { path = "../common" }
colored = "2.0"