name: CI Build App

on:
  push:
    branches: [main]
    paths:
      - 'common/**'
      - 'interpreter/**'
      - 'lexer/**'
      - 'parser/**'      
  pull_request:
    paths:
      - 'common/**'
      - 'interpreter/**'
      - 'lexer/**'
      - 'parser/**'    
  workflow_dispatch:



env:
  project_name: address-lang

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Test
          run: cargo test
          env:
            RUSTFLAGS: -Aunused_variables
    build:
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v3
                - name: Setup Rust
                  uses: actions-rust-lang/setup-rust-toolchain@v1
                - name: Test
                  run: cargo build
                  env:
                    RUSTFLAGS: -Aunused_variables
    formatting:
            name: cargo fmt
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: actions-rust-lang/setup-rust-toolchain@v1
                with:
                  components: rustfmt
              - name: Rustfmt Check
                uses: actions-rust-lang/rustfmt@v1